/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package simulacionindustrial;

import java.awt.Image;
import java.awt.Toolkit;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;


public class VentanaSimulacion extends javax.swing.JFrame {
    
     int elementoA, elementoB, peso = 0;
     boolean ciclo1 = false;
     boolean ciclo2 = false;
     boolean ciclo3 = false;

    /**
     * Creates new form NewJFrame
     */
    public VentanaSimulacion() {
        initComponents();
        
        startSimulation.setEnabled(true);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cementLabel = new javax.swing.JLabel();
        sandLabel = new javax.swing.JLabel();
        labelSensorPesoArena = new javax.swing.JLabel();
        motor = new javax.swing.JLabel();
        labelVascula = new javax.swing.JLabel();
        nombre1 = new javax.swing.JLabel();
        nombre2 = new javax.swing.JLabel();
        labelSensorPesoCemento = new javax.swing.JLabel();
        labelMezclaLista = new javax.swing.JLabel();
        nombre3 = new javax.swing.JLabel();
        valvulas = new javax.swing.JLabel();
        startSimulation = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cementLabel.setFont(new java.awt.Font("Cantarell", 1, 24)); // NOI18N
        cementLabel.setForeground(java.awt.Color.white);
        cementLabel.setText("FULL");
        getContentPane().add(cementLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, -1, 40));

        sandLabel.setFont(new java.awt.Font("Cantarell", 1, 24)); // NOI18N
        sandLabel.setForeground(java.awt.Color.white);
        sandLabel.setText("FULL");
        getContentPane().add(sandLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 100, -1, 30));

        labelSensorPesoArena.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/out.png"))); // NOI18N
        getContentPane().add(labelSensorPesoArena, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 50, 50, 50));

        motor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/mezcladora.png"))); // NOI18N
        getContentPane().add(motor, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 400, 190, 270));

        labelVascula.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        labelVascula.setForeground(java.awt.Color.white);
        labelVascula.setText("Peso Recibido: 0");
        getContentPane().add(labelVascula, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 300, 180, 40));

        nombre1.setText("Elemento A completo");
        getContentPane().add(nombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 120, -1, -1));

        nombre2.setText("Elemento B completo");
        getContentPane().add(nombre2, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 270, -1, 30));

        labelSensorPesoCemento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/out.png"))); // NOI18N
        getContentPane().add(labelSensorPesoCemento, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 200, 50, 50));

        labelMezclaLista.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/out.png"))); // NOI18N
        getContentPane().add(labelMezclaLista, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 340, 50, 50));

        nombre3.setText("Mezcla completa.");
        getContentPane().add(nombre3, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 400, 130, 40));

        valvulas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/tuberias.png"))); // NOI18N
        getContentPane().add(valvulas, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 380, 380));

        startSimulation.setText("Iniciar Simulacion");
        startSimulation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startSimulationActionPerformed(evt);
            }
        });
        getContentPane().add(startSimulation, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 480, -1, -1));

        jPanel1.setBackground(java.awt.Color.white);
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, 670));

        pack();
    }// </editor-fold>//GEN-END:initComponents

  
    
    
    private void sandSwitchActionPerformed2() {                                           
        
         labelVascula.setText("Peso Recibido: " + peso);
        new Thread () {
            @Override
            public void run(){
                for (peso = 0; peso <= 40; peso++) {
                    
                    if(elementoA == 0){
                        labelSensorPesoArena.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/in.png"))); 
                        ciclo1 =true;
                    }

                    sandLabel.setText("" + elementoA);
                    labelVascula.setText("Peso Recibido: " + peso);
                    
                    try {
                        Thread.sleep(500);
                    } catch (InterruptedException ex) {
                        Logger.getLogger(VentanaSimulacion.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    elementoA--;
                  } 
                
            vaciaContenedorArena();
            }
        }.start();
        
     
    }       
    
    private void vaciaContenedorArena() {                                           
        
         labelVascula.setText("Peso Recibido: " + peso);
        new Thread () {
            @Override
            public void run(){
                    labelSensorPesoArena.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/out.png"))); 
                for (peso = 40; peso >= 0; peso--) {
                        
                    labelVascula.setText("Peso Recibido: " + peso);
                    
                    try {
                        Thread.sleep(500);
                    } catch (InterruptedException ex) {
                        Logger.getLogger(VentanaSimulacion.class.getName()).log(Level.SEVERE, null, ex);
                    }
                  } 
                
                cementSwitchActionPerformed2();
            }
        }.start();
        
     
    } 
    
    private void cementSwitchActionPerformed2() {                                             
         
         labelSensorPesoArena.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/out.png"))); 
         labelSensorPesoCemento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/out.png"))); 
        
      
        new Thread () {
            @Override
            public void run(){
                for (peso = 0 ; peso <=40; peso++) {
                    
                    if(elementoB == 0){
                        labelSensorPesoCemento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/in.png"))); 
                        ciclo2 = false;
                    }

                    cementLabel.setText("" + elementoB);
                     labelVascula.setText("Peso Recibido: " + peso);
                    
                    try {
                        Thread.sleep(500);
                    } catch (InterruptedException ex) {
                        Logger.getLogger(VentanaSimulacion.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    elementoB--;
                  } 
                
        vaciaContenedorCemento();
            }
        }.start();
        
       
    } 
    
    private void vaciaContenedorCemento() {                                           
        
         labelVascula.setText("Peso Recibido: " + peso);
        new Thread () {
            @Override
            public void run(){
                    labelSensorPesoCemento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/out.png"))); 
                for (peso = 40; peso >= 0; peso--) {
                        
                    labelVascula.setText("Peso Recibido: " + peso);
                    
                    try {
                        Thread.sleep(500);
                    } catch (InterruptedException ex) {
                        Logger.getLogger(VentanaSimulacion.class.getName()).log(Level.SEVERE, null, ex);
                    }
                  } 
                motorSwitchActionPerformed2();
            }
        }.start();
        
     
    } 
    
    private void motorSwitchActionPerformed2() {                                            
        motor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/mezcladora.gif"))); 
        
        
         new Thread () {
            @Override
            public void run(){
                    try {
                        Thread.sleep(3000);
                        motor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/mezcladora.png"))); 
                        labelMezclaLista.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/in.png")));
                        ciclo3 = true;
                    } catch (InterruptedException ex) {
                        Logger.getLogger(VentanaSimulacion.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    startSimulation.setEnabled(true);
            }
        }.start();
        
    }
    
    private void startSimulationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startSimulationActionPerformed
        startSimulation.setEnabled(false);
        //printf("SADAS","ASDSAD");
        labelMezclaLista.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/out.png"))); 
        labelSensorPesoArena.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/out.png"))); 
        labelSensorPesoCemento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/out.png"))); 
        motor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/mezcladora.png")));
        
        elementoA = elementoB = peso = 0;
        ciclo1 = false;
        ciclo2 = false;
        ciclo3 = false;
        
        elementoA = 40;
        elementoB = 40;

        sandLabel.setText("FULL");
        cementLabel.setText("FULL");
        
        
        new Thread () {
            @Override
            public void run(){
                    sandSwitchActionPerformed2();
            }
        }.start();

        
    }//GEN-LAST:event_startSimulationActionPerformed

    public boolean getHilo1(){
        return  ciclo1;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaSimulacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaSimulacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaSimulacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaSimulacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaSimulacion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cementLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelMezclaLista;
    private javax.swing.JLabel labelSensorPesoArena;
    private javax.swing.JLabel labelSensorPesoCemento;
    private javax.swing.JLabel labelVascula;
    private javax.swing.JLabel motor;
    private javax.swing.JLabel nombre1;
    private javax.swing.JLabel nombre2;
    private javax.swing.JLabel nombre3;
    private javax.swing.JLabel sandLabel;
    private javax.swing.JButton startSimulation;
    private javax.swing.JLabel valvulas;
    // End of variables declaration//GEN-END:variables
}

